<div class="help-content-wrap"><h3 id="d-betting-procedures">D. BETTING PROCEDURES</h3>
<ol>
<li><p>Placing Bets</p>
<p>1.1 SportyBet reserves the right to decline all, or part, of any bet requested at its sole and absolute discretion. All bets are placed at your own risk and discretion.</p>
<p>1.2 We only accept bets made online (including via mobile device or downloadable applications on a mobile device). Bets are not accepted in any other form (ost, email, fax, etc.) and where received will be invalid and void - win or lose.</p>
<p>1.3 It is the responsibility of the customer to ensure details of their bets are correct. Once bets have been placed they may not be cancelled or changed by the customer. SportyBet reserves the right to cancel any bet at any time.</p>
<p>1.4 Your funds will be allocated to bets in the order they are placed and will not be available for any other use. SportyBet reserves the right to void and/or reverse any transactions made after a bet has been placed involving allocated funds, either at the time or retrospectively.</p>
</li>
<li><p>Bet Confirmation</p>
<p>2.1 Bets will not be valid if there are insufficient funds in your account.</p>
<p>2.2 A bet that you request will only be valid once accepted by SportyBet’s servers. Each valid bet will receive a unique transaction code. We shall not be liable for the settlement of any bets which are not issued with a unique transaction code. If you are unsure about the validity of a bet, please check your account history, or contact us.</p>
<p>2.3 Notwithstanding the above, if bets are placed via a credit or debit card they are not valid until we have received payment in full. The bet will be automatically void if we have not received the payment prior to the relevant event commencing.</p>
<p>2.4 Should a dispute arise, you and SportyBet agree that the SportyBet transaction log database will be the ultimate authority in such matters.</p>
</li>
<li><p>Offers</p>
<p>3.1 All customer offers are limited to one per person, family, household address, email address, telephone number, mobile device (e.g. mobile or tablet), application download or shared computer (e.g. public library or workplace).</p>
<p>3.2 Where any term of the offer or promotion is breached or there is any evidence of a series of bets placed by a customer or group of customers (e.g. where common betting patterns across the same fixture/markets have been identified across accounts), which due to a deposit bonus, enhanced payments, free and risk free bets, or any other promotional offer results in guaranteed customer profits irrespective of the outcome, whether individually or as part of a group, SportyBet reserves the right to reclaim the bonus element of such offers and in SportyBet’s absolute discretion settle bets at the correct odds, void the free and risk free bets or void any bet funded by the deposit bonus. In addition, SportyBet reserves the right to levy an administration charge on the customer up to the value of the deposit bonus, free and risk free bet or additional payment to cover administrative costs. SportyBet further reserves the right to ask any customer to provide sufficient documentation for SportyBet to be satisfied in its absolute discretion as to the customer’s identity prior to SportyBet crediting any bonus, free and risk free bet or offer to the customer’s account.</p>
<p>3.3 SportyBet reserves the right to withdraw the availability of any offer or all offers to any customer or group of customers at any time and at SportyBet’s sole and absolute discretion. Offers only apply to customers who have made an actual/real money deposit with SportyBet.</p>
<p>3.4 SportyBet reserves the right to amend the terms of or cancel any customer offer or promotion at any time.</p>
</li>
<li><p>Settlement and Payouts</p>
<p>4.1 All bets are subject to the Rules for the relevant sport / market / game set out in the How to play section and the provisions set out in Appendix Two to these Terms and Conditions.</p>
<p>4.2 SportyBet reserves the right to suspend a market and/or cancel any bet at any time. When a market is suspended any bets entered will be rejected. SportyBet also reserves the right to cease betting on any markets at any time without notice.</p>
<p>4.3 The &quot;Potential Win&quot; calculation available on the Website is for information purposes only, and all bets will be calculated using the stake/risk at the odds accepted. In multiple bets/parlays with a void selection(s) the &quot;Potential Win&quot; figure is reduced accordingly.</p>
<p>4.4 Should a customer include a non-runner or void selection in a multiple bet/parlay, the bet will be settled on the remaining selections.</p>
<p>4.5 Winnings from settled bets are added to the balance of your betting account. Any funds/winnings credited to an account in error are not available for use, and SportyBet reserves the right to void any transactions involving such funds and/or withdraw the relevant amount from your account and/or reverse the transaction, either at the time or retrospectively.</p>
<p>4.6 SportyBet reserves the right to withhold payment and to declare bets on an event void if we have evidence that the following has occurred: (i) the integrity of the event has been called into question; (ii) the price(s) or pool has been manipulated; or (iii) match-rigging has taken place. Evidence of the above may be based on the size, volume or pattern of bets placed with SportyBet across any or all of our betting channels. Any decision made by SportyBet in this regard will be conclusive. If any customer owes any money to SportyBet for any reason, we have the right to take that into account before making any payments to that customer.</p>
<p>4.7 Where there is evidence of a series of bets each containing the same selection(s) having been placed by or for the same individual or syndicate of individuals, SportyBet reserves the right to make bets void or withhold payment of returns pending the outcome of any subsequent investigation.</p>
<p>4.8 For events where there is no official &quot;off&quot; declared, the advertised start time of the event will be deemed the &#39;off&#39;. If for any reason a bet is inadvertently accepted after an event or match has commenced (other than live In-Play betting clearly indicated on the Website), bets will stand providing the final outcome is not known, and that no participant/team has gained any material advantage (e.g. a score, sending off for the other team, etc.) at the time the bet was placed. If the outcome of an event/market is known SportyBet reserves the right to void the bet, win or lose. Disputes over times bets are placed will be settled using the transaction log. All times stated on the Website and/or referred to by SportyBet staff relate to GMT unless stated otherwise.</p>
<p>4.9 In-Play Betting - where we have reason to believe that a bet is placed after the outcome of an event is known, or after the selected participant or team has gained a material advantage (e.g. a score, sending off for the other team etc.) we reserve the right to void the bet, win or lose.</p>
<p>4.10 If for any reason we are unable to validate the outcome of a particular market (e.g. due to loss of live pictures), all bets will be void, unless settlement of bets is already determined.</p>
<p>4.11 Where a customer gives ambiguous instructions, SportyBet reserves the right to split the amount of monies staked between the potential outcomes. Where this is impractical we reserve the right to void the whole of that bet. In any event, the decision of SportyBet is final.</p>
</li>
</ol>
</div>