<div class="help-content-wrap"><h3 id="h-other-provisions">H. OTHER PROVISIONS</h3>
<ol>
<li><p>These Terms and Conditions, the Privacy Policy, the Cookies Policy and any document expressly referred to in them and any guidelines or rules posted on the Website constitute the entire agreement and understanding of the parties and supersede any previous agreement between the parties relating to their subject matter. You acknowledge and agree that in entering into and agreeing to these Terms and Conditions, the Privacy Policy, the Cookies Policy and any document expressly referred to in them and any guidelines or rules posted on the Website you do not rely on, and shall have no remedy in respect of, any statement, representation, warranty, understanding, promise or assurance (whether negligently or innocently made) of any person (whether party to this agreement or not) other than as expressly set out therein. Nothing in this clause shall operate to limit or exclude any liability for fraud or fraudulent misrepresentation.</p>
</li>
<li><p>In no event will any delay, failure or omission (in whole or in part) in enforcing, exercising or pursuing any right, power, privilege, claim or remedy conferred by or arising under these Terms and Conditions or by law, be deemed to be or construed as a waiver of that or any other right, power, privilege, claim or remedy in respect of the circumstances in question, or operate so as to bar the enforcement of that, or any other right, power, privilege, claim or remedy, in any other instance at any time or times subsequently.</p>
</li>
<li><p>The rights and remedies provided by these Terms and Conditions are cumulative and (unless otherwise provided in these Terms and Conditions) do not exclude any other rights or remedies available in law.</p>
</li>
<li><p>If any provision of these Terms and Conditions is found by any court or administrative body of competent jurisdiction to be invalid or unenforceable, such invalidity or unenforceability shall not affect the other provisions of these Terms and Conditions which shall remain in full force and effect.</p>
</li>
<li><p>You shall execute or cause to be executed all documents and do or cause to be done all further acts and things consistent with the terms of these Terms and Conditions that SportyBet may from time to time reasonably require in order to vest in and secure to SportyBet the full benefit of rights and benefits to be transferred or granted to SportyBet under these Terms and Conditions and for the protection and enforcement of the same and otherwise to give full effect to the terms of these Terms and Conditions.</p>
</li>
<li><p>Nothing in these Terms and Conditions shall create or be deemed to create a partnership, joint venture or principal-agent relationship between the parties and no party shall have authority to bind any other in any way unless expressly provided otherwise in these Terms and Conditions.</p>
</li>
<li><p>SportyBet shall not be in breach of these Terms and Conditions nor liable for delay in performing, or failure to perform, any of its obligations if such delay or failure results from events, circumstances or causes beyond its reasonable control including (without limitation) any telecommunications network failures, power failures, failures in third party computer hardware or software, fire, lightning, explosion, flood, severe weather, industrial disputes or lock-outs, terrorist activity and acts of government or other competent authorities. In such circumstances the time for performance shall be extended by a period equivalent to the period during which performance of the obligation has been delayed or failed to be performed.</p>
</li>
<li><p>SportyBet may assign, transfer, charge, sub-license or deal in any other manner with these Terms and Conditions, or sub-contract any of its rights and obligations under these Terms and Conditions, to any party including any company within the SportyBet group.</p>
</li>
<li><p>Any notice to be given under these Terms and Conditions must be in writing, in English and may be served by hand delivery, first class post, recorded delivery or registered post or airmail, email or fax to: (a) in the case of SportyBet , the address of the relevant SportyBet company as set out at the beginning of these Terms and Conditions or as displayed on the Website; and (b) in respect of notices given by SportyBet to you, pursuant to the customer registration procedure (including any amendment to those details you have notified to SportyBet). Any notice shall be deemed to have been received: (a) if delivered by hand, at the time of delivery; (b) if sent by first class post, recorded delivery or registered post, at 09.30 (GMT) on the second clear day after the date of posting; (c) if sent by pre-paid registered airmail, at 09.30 (GMT) on the fifth clear day after the date of posting; (d) if sent by email, at the time of sending; and (e) if sent by fax, at the time of transmission by the sender.</p>
</li>
<li><p>The Appendices, the Privacy Policy, and any document expressly referred to in them and any guidelines or rules posted on the Website form an integral part of these Terms and Conditions and shall have effect as if set out in full in the body of these Terms and Conditions. In the event of any inconsistency between the main body of these Terms and Conditions and the Appendices, the Privacy Policy, and/or any document expressly referred to in them and any guidelines or rules posted on the Website, unless stated otherwise, the main body shall prevail.</p>
</li>
</ol>
</div>