<div class="help-content-wrap"><h3 id="e-use-of-the-website">E. USE OF THE WEBSITE</h3>
<ol>
<li><p>Information and Content</p>
<p>1.1 Information accessed by you on the Website (including results, statistics, sporting data and fixture lists, odds and betting figures) is for your personal use only and the distribution or commercial exploitation of such information is strictly prohibited. No warranty is given as to the uninterrupted provision of such information, its accuracy or as to the results obtained through its use. It should not be relied upon when placing bets, which are made at your own risk and discretion.</p>
</li>
<li><p>Your Equipment</p>
<p>2.1 Your computer equipment or mobile device and internet connection may affect the performance and/or operation of the Website. SportyBet does not guarantee that the Website will operate without faults or errors or that the SportyBet services will be provided without interruption. SportyBet does not accept any liability for any failures or issues that arise due to your equipment, internet connection or internet or telecommunication service provider (including, for example, if you are unable to place bets or to view or receive certain information in relation to particular events).</p>
<p>2.2 For customers using SportyBet’s mobile sites for the placing of bets, please note that SportyBet will not be responsible for any damage to, or loss of data from the mobile device that the software is installed on, and will also not be responsible for any call, data or other charges incurred whilst using the software.</p>
</li>
<li><p>Fair Use</p>
<p>3.1 The Website and SportyBet products may only be used for the purposes of placing bets on events and/or gaming products.</p>
<p>3.2 You must not use the Website for any purpose which (in SportyBet’s opinion) is illegal, defamatory, abusive or obscene, or which SportyBet considers discriminatory, fraudulent, dishonest or inappropriate.</p>
<p>3.3 SportyBet will seek criminal and contractual sanctions against any customer involved in fraudulent, dishonest or criminal acts via or in connection with the Website or SportyBet&#39;s products. SportyBet will withhold payment to any customer where any of these are suspected. The customer shall indemnify and shall be liable to pay to SportyBet, on demand, all Claims (as defined in paragraph B.4.3 above) arising directly or indirectly from the customer’s fraudulent, dishonest or criminal act.</p>
</li>
<li><p>Software and Technology Issues</p>
<p>4.1 In order for you to use certain products offered on the Website you may need to download some software (for example, casino games that are made available via a flash player). Also, certain third party product providers may require you to agree to additional terms and conditions governing the use of their products. If you do not accept those third party terms and conditions, do not use the relevant third party software. SportyBet does not accept any liability in respect of any third party software.</p>
<p>4.2 You are only permitted to use any and all software made available to you via the Website for the purpose of using products on the Website and, save to the extent permitted by applicable law, for no other purposes whatsoever.</p>
<p>4.3 We hereby grant to you a personal, non-exclusive, non-transferable right to use the relevant software, for the sole purpose of using/playing products on the Website (including the online casino), in accordance with the following provisions.</p>
<p> (a) You are not permitted to: (i) install or load the software onto a server or other networked device or take other steps to make the software available via any form of &quot;bulletin board&quot;, online service or remote dial-in or network to any other person; (ii) sub-license, assign, rent, lease, loan, transfer or copy (except as expressly provided elsewhere in these terms and conditions) your licence to use the software or make or distribute copies of the software; (iii) enter, access or attempt to enter or access or otherwise bypass SportyBet’s security system or interfere in any way (including but not limited to, robots and similar devices) with the relevant products or the Website or attempt to make any changes to the software and/or any features or components thereof; or (iv) copy or translate any user documentation provided &#39;online&#39; or in electronic format. In addition, and except to the minimum extent permitted by applicable law in relation to computer programs (including, the purposes expressly permitted by Section 296A(1) or Section 50(B)2 of the Copyright Designs and Patents Act 1988), you are not permitted to: (a) translate, reverse engineer, decompile, disassemble, modify, create derivative works based on, or otherwise modify the software; or (b) reverse engineer, decompile, disassemble, modify, adapt, translate, make any attempt to discover the source code of the software or to create derivative works based on the whole or on any part of the software.</p>
<p> (b) You do not own the software. The software is owned and is the exclusive property of SportyBet or a third party software provider company (the &quot;Software Provider&quot;). Any software and accompanying documentation which have been licensed to SportyBet are proprietary products of the Software Provider and protected throughout the world by copyright law. Your use of the software does not give you ownership of any intellectual property rights in the software.</p>
<p> (c) The software is provided &quot;as is&quot; without any warranties, conditions, undertakings or representations, express or implied, statutory or otherwise. SportyBet hereby excludes all implied terms, conditions and warranties (including any of merchantability, satisfactory quality and fitness for any particular purpose). SportyBet does not warrant that: (i) the software will meet your requirements; (ii) the software will not infringe any third party’s intellectual property rights; (iii) the operation of the software will be error free or uninterrupted; (iv) any defects in the software will be corrected; or (v) the software or the servers are virus-free.</p>
<p> (d) In the event of communications or system errors occurring in connection with the settlement of accounts or other features or components of the software, neither SportyBet nor the Software Provider will have any liability to you or to any third party in respect of such errors. SportyBet reserves the right in the event of such errors to remove all relevant products from the Website and take any other action to correct such errors.</p>
<p> (e) You hereby acknowledge that how you use the software is outside of SportyBet’s control. Accordingly, you load and use the software at your own risk. SportyBet will not have any liability to you or to any third party in respect of your receipt of and/or use of the software.</p>
<p> (f) The software may include confidential information which is secret and valuable to the Software Provider and/or SportyBet. You are not entitled to use or disclose that confidential information other than strictly in accordance with these Terms and Conditions.</p>
<p>4.4 While SportyBet endeavours to ensure that the Website is available 24 hours a day, SportyBet shall not be liable if for any reason the Website is unavailable at any time or for any period. We reserve the right to make changes or corrections to or to alter, suspend or discontinue any aspect of the Website and the content or services or products available through it, including your access to it.</p>
<p>4.5 You must not misuse the Website by introducing viruses, Trojans, worms, logic bombs or other material which is malicious or technologically harmful. In particular, you must not access without authority, interfere with, damage or disrupt the Website or any part of it; any equipment or network on which the Website is stored; any software used in connection with the provision of the Website; or any equipment, software or website owned or used by a third party. You must not attack our Website via a denial-of-service attack. We will not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of the Website, software or to your downloading of any material posted on it, or on any website linked to it.</p>
</li>
<li><p>Third Party Content</p>
<p>5.1 SportyBet receives feeds, commentaries and content from a number of suppliers. Certain third party product providers may require you to agree to additional terms and conditions governing the use of their feeds, commentaries and content. If you do not accept the relevant third party terms and conditions, do not use the relevant feeds, commentaries or content.</p>
<p>5.2 SportyBet does not accept any liability in respect of any third party feeds, commentaries and content.</p>
<p>5.3 SportyBet does not allow any employee, anyone else in any way connected to such employee or anyone otherwise connected to a third party service provider (to be determined in SportyBet’s absolute discretion) to bet/wager on any market or event where the third party service provider is providing a service to SportyBet . SportyBet will void any bet/wager where it determines in its absolute discretion that such betting/wagering has taken place.</p>
<p>5.4 Where the Website contains links to third party websites and resources, these links are provided for your information only. SportyBet has no control over the content of these sites or resources, and accepts no liability for them or for any loss or damage that may arise from your use of them. The inclusion of a link to a third party website does not constitute an endorsement of that third party’s website, product or services (if applicable).</p>
</li>
<li><p>Errors</p>
<p>6.1 SportyBet will not be liable for any errors in respect of bets including where: (i) SportyBet has incorrectly stated the relevant odds/spreads/handicap/totals amount; (ii) SportyBet continues to accept bets on closed or suspended markets; (iii) SportyBet incorrectly calculates or pays a settlement amount; or (iv) any error occurs in a random number generator or pay tables included, incorporated or used in any game or product.</p>
<p>6.2 Incorrect Price - Prior to the start of an event, In-Play or after the event, where an Obvious Error is identified any bets will stand and be settled at the SportyBet revised price. Where a revised price is deemed less than 1.01 then bets will be void.</p>
<p> Where there is sufficient time before the start of an event, SportyBet will endeavour to contact the customer and may allow the option of cancelling the bet in our absolute discretion.</p>
<p>6.3 Incorrect Count/Line/Spread/Handicap/Total - Prior to the start of an event, In-Play or after the event, where an Obvious Error is identified any bets will stand and be settled at the count, line, spread, handicap or total taken at the SportyBet revised price except for the following situations:</p>
<p> i) Where a revised price is deemed less than 1.01 then bets will be void.</p>
<p> ii) Any bet placed on a count, line, spread, handicap or total where the outcome is already known when the bet was placed will be void.</p>
<p>6.4 Where there is sufficient time before the start of an event, SportyBet will endeavour to contact the customer and may in our absolute discretion allow the option of cancelling the bet.</p>
<p>6.5 Incorrect Fixture - Where the wrong player or team is quoted within a fixture name all bets will be void. Such determination to be in SportyBet’s absolute discretion.</p>
<p>6.6 Wrong Participant - If a wrong participant is quoted for any match or event, bets placed on that participant will be void; other participants may also be void. Such determination to be in SportyBet’s absolute discretion.</p>
<p>6.7 Late Bets - If for any reason a pre-event bet is inadvertently accepted after a match or event has commenced, bets will be settled as follows:</p>
<p> i) If the event and market is covered In-Play then bets will stand at the revised price at the time the bet was placed (where a revised price is deemed less than 1.01 then bets will be void), unless the outcome is already known in which case such bets will be void.</p>
<p> ii) If the event or market is not covered In-Play then the bet will stand as long as the selected participant or team has not gained a material advantage (e.g. a score, sending off for the other team etc.). Where a material advantage has been gained SportyBet reserve the right to void the bet, win or lose. Any bet placed where the outcome is already known, including In-Play, will be made void.</p>
<p>6.9 Obvious Error - Maximum Winnings - The maximum amount which can be won for a bet placed where there is an Obvious Error and a revised price is USD 5,000 or its equivalent, unless the expected winning amount of the original bet was greater than USD 5,000 or its equivalent. In such circumstances, the winning amount of the bet placed at the revised price will equal that of the original bet with any excess stake becoming void.</p>
</li>
<li><p>Other</p>
<p>7.1 SportyBet actively monitors traffic to and from the Website. SportyBet reserves the right in its sole discretion to block access where evidence indicative of automated or robotic activity is found.</p>
<p>7.2 SportyBet reserves the right to restrict access to all or certain parts of the Website in respect of certain jurisdictions.</p>
<p>7.3 SportyBet may alter or amend the products offered via the Website at any time and for any reason.</p>
<p>7.4 From time to time, all or part of the Website may be unavailable for use by you because of our maintenance of the Website and/or alteration or amendment of any of the Website products.</p>
</li>
</ol>
</div>